services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=it_incidents_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  pgdb:
    image: dpage/pgadmin4
    container_name: pgdb
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - pgdb_data:/var/lib/pgadmin

volumes:
  db_data:
    driver: local
  pgdb_data:
    driver: local